### ISSUE TITLE
Watch not works

### ISSUE THREAD

**Issue by seb-jean** [SymfonyCasts/tailwind-bundle#14]
Hi,

The CSS is not compiled for the watch.

This is the command I run.:
`php bin/console tailwind:build --watch`

**Comment by weaverryan** [comment]
It works fine for me - could it be another windows thing? What output do you see? Is the var/tailwind/tailwind.built.css file created at all?

**Comment by seb-jean** [comment]
> Is the var/tailwind/tailwind.built.css file created at all?

No, the content of this file does not change.

**Comment by weaverryan** [comment]
@seb-jean could you try https://github.com/SymfonyCasts/tailwind-bundle/pull/15 ? It's my next guess to get this to work cross-platform :)
