### ISSUE TITLE
Watch + refresh does not update asset css

### ISSUE THREAD

**Issue by back-2-95** [SymfonyCasts/tailwind-bundle#27]
I have watch mode running with in my Symfony 7.0.0-BETA3 project:

```console
bin/console tailwind:build --watch
```

It will successfully build `var/tailwind/tailwind.build.css` with any changes to `assets/styles/app.css`.

BUT when refreshing the app in browser, changes don't get updated. When I check `public/assets/styles/app-HASH.css` it has not been updated.

In `base.html.twig` I have following inside <head>

```
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
            {{ importmap('app') }}
        {% endblock %}
```

which will create following markup:

![image](https://github.com/SymfonyCasts/tailwind-bundle/assets/1140272/ce1a67e3-bbfa-4e62-88f9-7bcfd783c4d5)

I also tried this as mentioned in the documention but to no luck:

```
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('styles/app.css') }}">
{% endblock %}
```

So I need to manually run these to get CSS updated:

```
bin/console tailwind:build
bin/console asset-map:compile
```

**Comment by back-2-95** [comment]
Issue remains.
- `var/tailwind/tailwind.build.css` is updated
- `public/assets/styles/app-hash.css` is NOT updated

when running `bin/console tailwind:build --watch`

I also checked that my Docker setup does not affect this. Same happens when I run that command on host and on container.

**Comment by fracsi** [comment]
@back-2-95 If you want to see the changes in the browser without compiling your assets every time after change, you should enable the "dev server" for the asset mapper (enabled by default only in "debug" mode)
See: `bin/console config:dump framework asset_mapper.server`

When this "dev server" is enabled, assets are handled by symfony  (they must not exist in the filesystem - remove publis/assets) - https://symfony.com/doc/current/frontend/asset_mapper.html#serving-assets-in-dev-vs-prod

**Comment by back-2-95** [comment]
@fracsi Thank you very much, now I got it working! `framework.asset_mapper_server: true` was the key!

**Comment by weaverryan** [comment]
Cool! Glad this got solved!
