### ISSUE TITLE
How can I use third party plugins with this bundle / tailwind.config.js?

### ISSUE THREAD

**Issue by toby-griffiths** [SymfonyCasts/tailwind-bundle#36]
Hello there 👋🏼

Thank you for all the work you've put into this plugin.

I have a question about using 3rd party plugins…. I've been wracking my brain to try to work out how to install the Flowbite plugin using Symfony's `importmap:require` command… and then I realised that the way I learned to include the `tailwindcss/plugin` as found in [this Symfonycast](https://symfonycasts.com/screencast/last-stack/turbo-frames#hiding-content-not-in-a-frame) works even when the project does not have any `tailwindcss` files in the `./assert/vendor` directory, so I have 2 questions…

1 . How does this code work? i.e. where is the plugin file actually found?  Is it inside the Tailwind binary, perhaps?…

    ```
    const plugin = require('tailwindcss/plugin');
    /** @type {import('tailwindcss').Config} */
    module.exports = {
      plugins: [
        plugin(function({ addVariant }) {
          addVariant('turbo-frame', 'turbo-frame[src] &')
        }),
      ],
    }
    ```

2. How can I install the Flowbite package plugin in a way it can be found by the `tailswindcss:build` process?

Here's how I've tried it…

1. Install flowbite…
```
$ symfony console importmap:require flowbite/plugin
```
2. Add flowbite to the `tailwindcss.config.js` file…
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./assets/**/*.js",
    "./templates/**/*.html.twig",
    "./vendor/tales-from-a-dev/flowbite-bundle/templates/**/*.html.twig"
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('flowbite/plugin'),
  ],
}

```
3. Attempt to build the tailwind files…
```
$ symfony console tailwindcss:build
```

And here's the error I'm getting…

```
Error: Cannot find module 'flowbite/plugin'
Require stack:
- /Users/toby/src/gitlab.com/toby-griffiths/project/tailwind.config.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at _resolve (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:250334)
    at jiti (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:252917)
    at /Users/toby/src/gitlab.com/toby-griffiths/project/tailwind.config.js:12:5
    at evalModule (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:255614)
    at jiti (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:253542)
    at /snapshot/tailwindcss/lib/lib/load-config.js:37:30
    at loadConfig (/snapshot/tailwindcss/lib/lib/load-config.js:39:6) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/toby/src/gitlab.com/toby-griffiths/project/tailwind.config.js'
  ]
}
```

**Comment by toby-griffiths** [comment]
And of course, immediately after I typed that I had another idea… and worked it out.

For anyone finding this and wondering the same thing, simply `npm init` in the same directory as the `tailwind.config.js` file, `npm install flowbite`, and then the TailwindCSS build should find it just dandy.

Do you know if this is likely to be updated to support the 'node/npm-less' approach we can now use with the release of the AssetMapper component?

**Comment by Inkod** [comment]
Hi @toby-griffiths :wave: 

I asked myself exactly the same question about this subject and came across this issue . I've found a solution (similar to yours):
- install flowbite plugin (like you did): 
```bash
$ symfony console importmap:require flowbite/plugin
```
- Enable plugin on tailwind (from path):
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./vendor/tales-from-a-dev/flowbite-bundle/templates/**/*.html.twig",
    "./assets/**/*.js",
    "./templates/**/*.html.twig",
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('./assets/vendor/flowbite/plugin.js'), // <===
  ],
}
```

Now, the tailwind build should work ;)

**Comment by toby-griffiths** [comment]
Thanks for the additional info @Inkod.  Sounds like a better fix might be required somehow.

**Comment by Inkod** [comment]
I tried multiples hack to find a way without to have to install package via npm but without success.. It helped me understand the whole system a little better.

In the case of a tailwind plugin that has no dependencies on other packages (except the tailwind packages themselves), there will be no problem using a path to the packages installed via AssetMapper. However, if the plugin has an another deps like `flowbite` with `mini-svg-data-uri`, tailwind build will try to found it in node_modules, but inevitably, there aren't any.

**Comment by Inkod** [comment]
Anyway, I think Tailwind is build to work with node to resolve child deps from plugins package, and so, it needs to have a package.json for each packages.. 

As a result, I don't know if there's much point in using the "AssetMapper" component if you want to be able to make full use of tailwind and the related plugins. WebpackEncore might seem more appropriate for the moment to avoid having to maintain both a list of packages via importmap and via npm.

**Comment by weaverryan** [comment]
Hey!

Tailwind is a pure Node package, so if it has any deps, those should be installed with npm. We now have a section that talks about this - https://symfony.com/bundles/TailwindBundle/current/index.html#tailwind-plugins - we also cover Flowbite specifically at the end of our latest tutorial - https://symfonycasts.com/screencast/last-stack/flowbite

Cheers!

**Comment by featuriz** [comment]
If I use symfony assert mapper, its not working. I tried the following both not working, after installing,

First, I installed by following [Symfony and Tailwind CSS starter project](https://github.com/themesberg/tailwind-symfony-starter)

`symfony console import:require flowbite` and `symfony console import:require flowbite/plugin`

```js
plugins: [
    require('@tailwindcss/typography'),
    require('./assets/vendor/flowbite/plugin')
  ],
```
and
```js
plugins: [
    require('@tailwindcss/typography'),
    require('flowbite/plugin')
  ],
```

**Comment by barbieswimcrew** [comment]
I tried using the "tailwindcss-debug-screens" plugin and it worked for me! Just installed it via asset mapper like so:

` php bin/console importmap:require tailwindcss-debug-screens`

After installing I added the following line to the tailwind.config.js:

```JS
plugins: [
    require('./assets/vendor/tailwindcss-debug-screens/tailwindcss-debug-screens.index'),
]
```

**Comment by SparkyRih** [comment]
I wanted to give the AssetMapper a try in a brand new project, but I can't get it to work with flowbite/plugin, tried everything mentioned here including a couple more things.

**Comment by luisibal** [comment]
> I wanted to give the AssetMapper a try in a brand new project, but I can't get it to work with flowbite/plugin, tried everything mentioned here including a couple more things.

I was struggling with this but the 'Solution' is not use the flowbite like this:

```
module.exports = {

    plugins: [
        require('flowbite/plugin')
    ]

}
```
Since this requires installing it with npm/ pnpm etc. and then flowbite/plugin looks up in the node_modules folder, that's why we get an error with AssetMapper because it doesn't use a node_modules folder. Using it like that was only one of the ways to use flowbite mentioned in the documentation. 

[https://flowbite.com/docs/getting-started/quickstart/](url)


but simple use like this:

`import 'flowbite';`

in your js file where you want to use it and you can still configure tailwind the usual way.

**Comment by kbond** [comment]
Hey @luisibal, does https://symfony.com/bundles/TailwindBundle/current/index.html#tailwind-plugins not work for you? I know it requires using npm which is a drag but I believe it's the only solution right now.
