### ISSUE TITLE
missing tailwind classes

### ISSUE THREAD

**Issue by jorguerra** [SymfonyCasts/tailwind-bundle#51]
I am using the bundle but there are some classes that I cannot find and I was wondering why.  When I checked the app.css on my local I see that I am working with Tailwind 3.4.3 which is the latest version but when I try to find the occurrences that start with `rounded-` I only find this six:

    .rounded-2xl {
      border-radius: 1rem;
    }
    
    .rounded-full {
      border-radius: 9999px;
    }
    
    .rounded-lg {
      border-radius: 0.5rem;
    }
    
    .rounded-md {
      border-radius: 0.375rem;
    }
    
    .rounded-sm {
      border-radius: 0.125rem;
    }

which means that all the classes like **rounded-r-lg, rounded-r-sm, rounded-t-sm**, and so on are missing. I cannot find **text-justify** either and many others

**Comment by bocharsky-bw** [comment]
Hm, Tailwind adds CSS classes to the CSS file only when you use them. Please, make sure you add the classes you need in your template first, e.g. `text-justify`, and then rerun the Tailwind `bin/console tailwind:build` so that it add new classes you're using in the CSS file

**Comment by jrushlow** [comment]
I'm going to close this as I believe @bocharsky-bw's comment should resolve your issue  - @jorguerra if you are still having trouble, please let us know and we can reopen it. 

Thanks!

**Comment by javiereguiluz** [comment]
@jorguerra if you build some CSS classes dynamically, Tailwind won't find those and they will never be added to the built CSS.

The solution is to use https://tailwindcss.com/docs/content-configuration#safelisting-classes E.g. this is a sample of what I have in my own `tailwind.config.js` file:

```js
module.exports = {
    content: [
        "./assets/**/*.js",
        "./templates/**/*.html.twig",
    ],
    safelist: [
        {
            pattern: /grid-(cols|rows)-*/,
            variants: ['sm', 'lg', 'xl'],
        },
        {
            pattern: /(col|row)-span-*/,
            variants: ['lg'],
        },
    ]
}
```

**Comment by bocharsky-bw** [comment]
Hey @javiereguiluz ,

Thanks for this tip!

P.S. I also noticed a "Tailwind CSS" PhpStorm plugin that I think might be useful for Tailwind auto-completion as well.

Cheers!
