### ISSUE TITLE
Windows Docker and Tailwind watch mode

### ISSUE THREAD

**Issue by Mitraniom** [SymfonyCasts/tailwind-bundle#56]
The watch mode on my project was not working.

I managed to get the watch mode working by adding `--poll` to the tailwind command.

For reference : https://github.com/tailwindlabs/tailwindcss/discussions/8100

Can we add a `--poll` option to the command, or is there another way to do it ?

**Comment by bocharsky-bw** [comment]
I think we can add this `--poll` option to the bundle if some people really need it and watching does not work for them. But I'm not sure we should enable this `--poll` along with `--watch` by default. As I see, we need a bool flag in the configuration that will either add this option to the final command or no.

Do you want to give it a try and implement this feature? A PR is warmly welcome on this issue
