### ISSUE TITLE
Add Inter font

### ISSUE THREAD

**Issue by seb-jean** [SymfonyCasts/tailwind-bundle#9]
Hi,

Would it be interesting to include the [Inter](https://rsms.me/inter/) font in this bundle?

Thanks

**Comment by weaverryan** [comment]
How so? When I use Inter, I use it via jsdelivr (or download it manually) - e.g. https://www.jsdelivr.com/package/npm/@fontsource/inter

Grabbing that is not as smooth as I would like it, but that's a shared problem with all 3rd party CSS + asset mapper, and something I'd like to address for AssetMapper 6.4. But did you have an alternative idea?

**Comment by seb-jean** [comment]
As for this repository: https://github.com/rails/tailwindcss-rails.

**Comment by weaverryan** [comment]
Huh, I'm not sure why they did that. It seems a bit random to choose just one font and automatically add it. So I'm 👎  and am in favor of making 3rd party CSS easier in general in AssetMapper 6.4. Thanks for the suggestion - I obviously modeled this bundle off of that library, but never noticed that!
